package org.jingfu.order.model;

// default package
// Generated 10/04/2015 11:02:55 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompletedOrder generated by hbm2java
 */
@Entity
@Table(name = "completed_order", catalog = "order_management")
public class CompletedOrder implements java.io.Serializable {

	private Integer completedOrderId;
	private byte tableNo;
	private BigDecimal billCharge;
	private Date createTime;
	private String createBy;
	private Set<CompletedDish> completedDishes = new HashSet<CompletedDish>(0);

	public CompletedOrder() {
	}

	public CompletedOrder(byte tableNo, Date createTime, String createBy) {
		this.tableNo = tableNo;
		this.createTime = createTime;
		this.createBy = createBy;
	}

	public CompletedOrder(byte tableNo, BigDecimal billCharge, Date createTime,
			String createBy, Set<CompletedDish> completedDishes) {
		this.tableNo = tableNo;
		this.billCharge = billCharge;
		this.createTime = createTime;
		this.createBy = createBy;
		this.completedDishes = completedDishes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "completed_order_id", unique = true, nullable = false)
	public Integer getCompletedOrderId() {
		return this.completedOrderId;
	}

	public void setCompletedOrderId(Integer completedOrderId) {
		this.completedOrderId = completedOrderId;
	}

	@Column(name = "table_no", nullable = false)
	public byte getTableNo() {
		return this.tableNo;
	}

	public void setTableNo(byte tableNo) {
		this.tableNo = tableNo;
	}

	@Column(name = "bill_charge", precision = 8)
	public BigDecimal getBillCharge() {
		return this.billCharge;
	}

	public void setBillCharge(BigDecimal billCharge) {
		this.billCharge = billCharge;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "create_by", nullable = false, length = 30)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "completedOrder")
	public Set<CompletedDish> getCompletedDishes() {
		return this.completedDishes;
	}

	public void setCompletedDishes(Set<CompletedDish> completedDishes) {
		this.completedDishes = completedDishes;
	}

}
