package org.jingfu.order.model;

// default package
// Generated 10/04/2015 11:02:55 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompletedDish generated by hbm2java
 */
@Entity
@Table(name = "completed_dish", catalog = "order_management")
public class CompletedDish implements java.io.Serializable {

	private Integer completedDishId;
	private CompletedOrder completedOrder;
	private String dishType;
	private String dishName;
	private int quantity;
	private BigDecimal unitPrice;
	private Date createTime;
	private String createBy;

	public CompletedDish() {
	}

	public CompletedDish(CompletedOrder completedOrder, String dishType,
			String dishName, int quantity, BigDecimal unitPrice,
			Date createTime, String createBy) {
		this.completedOrder = completedOrder;
		this.dishType = dishType;
		this.dishName = dishName;
		this.quantity = quantity;
		this.unitPrice = unitPrice;
		this.createTime = createTime;
		this.createBy = createBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "completed_dish_id", unique = true, nullable = false)
	public Integer getCompletedDishId() {
		return this.completedDishId;
	}

	public void setCompletedDishId(Integer completedDishId) {
		this.completedDishId = completedDishId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "completed_order_id", nullable = false)
	public CompletedOrder getCompletedOrder() {
		return this.completedOrder;
	}

	public void setCompletedOrder(CompletedOrder completedOrder) {
		this.completedOrder = completedOrder;
	}

	@Column(name = "dish_type", nullable = false, length = 12)
	public String getDishType() {
		return this.dishType;
	}

	public void setDishType(String dishType) {
		this.dishType = dishType;
	}

	@Column(name = "dish_name", nullable = false, length = 50)
	public String getDishName() {
		return this.dishName;
	}

	public void setDishName(String dishName) {
		this.dishName = dishName;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "unit_price", nullable = false, precision = 5)
	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "create_by", nullable = false, length = 30)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

}
