package org.jingfu.order.model;

// default package
// Generated 10/04/2015 11:02:55 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProcessingOrder generated by hbm2java
 */
@Entity
@Table(name = "processing_order", catalog = "order_management")
public class ProcessingOrder implements java.io.Serializable, Comparable<ProcessingOrder> {

	private Integer processingOrderId;
	private byte tableNo;
	private String status;
	private Date createTime;
	private Date updateTime;
	private String createBy;
	private String updateBy;
	private Set<ProcessingDish> processingDishes = new HashSet<ProcessingDish>(
			0);

	public ProcessingOrder() {
	}

	public ProcessingOrder(byte tableNo, String status, Date createTime,
			String createBy) {
		this.tableNo = tableNo;
		this.status = status;
		this.createTime = createTime;
		this.createBy = createBy;
	}

	public ProcessingOrder(byte tableNo, String status, Date createTime,
			Date updateTime, String createBy, String updateBy,
			Set<ProcessingDish> processingDishes) {
		this.tableNo = tableNo;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.createBy = createBy;
		this.updateBy = updateBy;
		this.processingDishes = processingDishes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "processing_order_id", unique = true, nullable = false)
	public Integer getProcessingOrderId() {
		return this.processingOrderId;
	}

	public void setProcessingOrderId(Integer processingOrderId) {
		this.processingOrderId = processingOrderId;
	}

	@Column(name = "table_no", nullable = false)
	public byte getTableNo() {
		return this.tableNo;
	}

	public void setTableNo(byte tableNo) {
		this.tableNo = tableNo;
	}

	@Column(name = "status", nullable = false, length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "create_by", nullable = false, length = 30)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Column(name = "update_by", length = 30)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "processingOrder", cascade=CascadeType.ALL)
	public Set<ProcessingDish> getProcessingDishes() {
		return this.processingDishes;
	}

	public void setProcessingDishes(Set<ProcessingDish> processingDishes) {
		this.processingDishes = processingDishes;
	}

	@Override
	public int compareTo(ProcessingOrder o) {
		return this.createTime.compareTo(o.getCreateTime());
	}
	
	/* not work in hibernate session
	@PrePersist
    protected void onCreate() {
		this.createTime = new Date();
    }

    @PreUpdate
    protected void onUpdate() {
    	this.updateTime = new Date();
    }
    */

}
