package org.jingfu.order.model;

// default package
// Generated 10/04/2015 11:02:55 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProcessingDish generated by hbm2java
 */
@Entity
@Table(name = "processing_dish", catalog = "order_management")
public class ProcessingDish implements java.io.Serializable {

	private Integer processingDishId;
	private ProcessingOrder processingOrder;
	private String dishType;
	private String dishName;
	private int quantity;
	private int quantityWaiting;
	private int quantityProcessing;
	private int quantityReady;
	private int quantityCompleted;
	private BigDecimal unitPrice;
	private String status;
	private Date createTime;
	private Date updateTime;
	private String createBy;
	private String updateBy;

	public ProcessingDish() {
	}

	public ProcessingDish(ProcessingOrder processingOrder, String dishType,
			String dishName, int quantity, BigDecimal unitPrice, String status,
			Date createTime, String createBy) {
		this.processingOrder = processingOrder;
		this.dishType = dishType;
		this.dishName = dishName;
		this.quantity = quantity;
		this.unitPrice = unitPrice;
		this.status = status;
		this.createTime = createTime;
		this.createBy = createBy;
	}

	public ProcessingDish(ProcessingOrder processingOrder, String dishType,
			String dishName, int quantity, BigDecimal unitPrice, String status,
			Date createTime, Date updateTime, String createBy, String updateBy) {
		this.processingOrder = processingOrder;
		this.dishType = dishType;
		this.dishName = dishName;
		this.quantity = quantity;
		this.unitPrice = unitPrice;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.createBy = createBy;
		this.updateBy = updateBy;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "processing_dish_id", unique = true, nullable = false)
	public Integer getProcessingDishId() {
		return this.processingDishId;
	}

	public void setProcessingDishId(Integer processingDishId) {
		this.processingDishId = processingDishId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "processing_order_id", nullable = false)
	public ProcessingOrder getProcessingOrder() {
		return this.processingOrder;
	}

	public void setProcessingOrder(ProcessingOrder processingOrder) {
		this.processingOrder = processingOrder;
	}

	@Column(name = "dish_type", nullable = false, length = 12)
	public String getDishType() {
		return this.dishType;
	}

	public void setDishType(String dishType) {
		this.dishType = dishType;
	}

	@Column(name = "dish_name", nullable = false, length = 50)
	public String getDishName() {
		return this.dishName;
	}

	public void setDishName(String dishName) {
		this.dishName = dishName;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	
	@Column(name = "quantity_waiting", nullable = false)
	public int getQuantityWaiting() {
		return this.quantityWaiting;
	}

	public void setQuantityWaiting(int quantityWaiting) {
		this.quantityWaiting = quantityWaiting;
	}
	
	@Column(name = "quantity_processing", nullable = false)
	public int getQuantityProcessing() {
		return this.quantityProcessing;
	}

	public void setQuantityProcessing(int quantityProcessing) {
		this.quantityProcessing = quantityProcessing;
	}
	
	@Column(name = "quantity_ready", nullable = false)
	public int getQuantityReady() {
		return this.quantityReady;
	}

	public void setQuantityReady(int quantityReady) {
		this.quantityReady = quantityReady;
	}
	
	@Column(name = "quantity_completed", nullable = false)
	public int getQuantityCompleted() {
		return this.quantityCompleted;
	}

	public void setQuantityCompleted(int quantityCompleted) {
		this.quantityCompleted = quantityCompleted;
	}

	@Column(name = "unit_price", nullable = false, precision = 5)
	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "status", nullable = false, length = 9)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "create_by", nullable = false, length = 30)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Column(name = "update_by", length = 30)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}
	
	/* not work in Hibernate Session
	 * 
	@PrePersist
    protected void onCreate() {
		this.createTime = new Date();
    }

    @PreUpdate
    protected void onUpdate() {
    	this.updateTime = new Date();
    }
    */

}
